// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXV_lZY61Znocg15-Fr-1IIoa135Y5Z2U',
    appId: '1:728451426777:web:aa6fb59f40ebe203cfd1c8',
    messagingSenderId: '728451426777',
    projectId: 'eclipse-02-spotify-clone',
    authDomain: 'eclipse-02-spotify-clone.firebaseapp.com',
    storageBucket: 'eclipse-02-spotify-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvDcDswwhDTbaTW8ccSM04_MjnnNIqi8U',
    appId: '1:728451426777:ios:87353ed6f6d65cc2cfd1c8',
    messagingSenderId: '728451426777',
    projectId: 'eclipse-02-spotify-clone',
    storageBucket: 'eclipse-02-spotify-clone.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvDcDswwhDTbaTW8ccSM04_MjnnNIqi8U',
    appId: '1:728451426777:ios:87353ed6f6d65cc2cfd1c8',
    messagingSenderId: '728451426777',
    projectId: 'eclipse-02-spotify-clone',
    storageBucket: 'eclipse-02-spotify-clone.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXV_lZY61Znocg15-Fr-1IIoa135Y5Z2U',
    appId: '1:728451426777:web:683186152988766fcfd1c8',
    messagingSenderId: '728451426777',
    projectId: 'eclipse-02-spotify-clone',
    authDomain: 'eclipse-02-spotify-clone.firebaseapp.com',
    storageBucket: 'eclipse-02-spotify-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWpe9sJHj3w2uSHK9RBd5p-bGgpIL58LI',
    appId: '1:728451426777:android:976fa5558093de2ecfd1c8',
    messagingSenderId: '728451426777',
    projectId: 'eclipse-02-spotify-clone',
    storageBucket: 'eclipse-02-spotify-clone.appspot.com',
  );

}